<Project>

  <PropertyGroup>

    <LangVersion>Preview</LangVersion>

    <DebugType>portable</DebugType>

    <PackageProjectUrl>https://github.com/LTRData/DiscUtils</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>

    <Company>LTR Data</Company>
    <Authors>Kenneth Bell;LordMike;Olof Lagerkvist</Authors>
    <OutputPath>..\$(Configuration)</OutputPath>
    <FileVersion>1.0.89</FileVersion>

	<GenerateDocumentationFile>true</GenerateDocumentationFile>

    <NoWarn>CS1591;CS0649</NoWarn>
    
  </PropertyGroup>

  <!-- Add PolySharp for supporting more recent language features -->
  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net5.0'))">
	<PackageReference Include="PolySharp" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
